---

services:
  zephyr-probe:
    build: .
    container_name: Zephyr-Probe
    ports:
      - "8000:8000"
    env_file:
      - .env
    stop_grace_period: 30s
    networks:
      - serge-external-network
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiochip4:/dev/gpiochip4"
    volumes:
      - /sys:/sys
      - /proc/device-tree:/proc/device-tree
      - ./data:/src/data

networks:
  serge-external-network:
    external: true
